# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

licenses:
  allowed:
    - Apache-2.0
    - MIT
    - BSD
    - ISC
    - (MIT AND CC-BY-3.0)
  warning:
    - LGPL-3.0
    - LGPL-2.0
    - MPL-2.0
    - EPL-1.0
    - CC-BY-4.0
    - Python-2.0
    - BlueOak-1.0.0
    - CC BY-SA 4.0
    - CC-BY-3.0
    - CC0-1.0
  forbidden:
    - AGPL-3.0
    - GPL-2.0
    - GPL-3.0
allowWarnings: true
# Options passed directly to the license-checker package
licenseCheckerOptions:
  # Global options are applied to all types of checks
  global:
    excludePrivatePackages: true
    excludePackages: "@cspell/dict-en-common-misspellings@2.0.7"
  # You can also specify options for each type of check. They extend the global options
  # warning:
    # excludePrivatePackages: false
  # forbidden:
    # excludePrivatePackages: false
